name: C/C++ Code Analysis

on: [push, pull_request]

jobs:
  cpp-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: List files (for debugging)
        run: ls -R

      - name: Run cppcheck on Philosophers problem
        run: cppcheck --enable=all --inconclusive Problem_jedzacych_filozofow/filoczas.cpp

      - name: Run cppcheck on Chat server
        run: cppcheck --enable=all --inconclusive chat2/server/main.c

      - name: Run cppcheck on Chat client
        run: cppcheck --enable=all --inconclusive chat2/client/main.c
